"""
Excel report builder using openpyxl.

Generates professionally formatted CA-ready Excel workbooks with:
- Cover page
- Balance Sheet (MCA Schedule III format)
- Statement of Profit & Loss
- Trial Balance
- Audit Findings Summary
- Detailed Audit Findings
"""

from __future__ import annotations

import logging
from decimal import Decimal
from io import BytesIO
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import (
    Alignment,
    Border,
    Font,
    PatternFill,
    Side,
    numbers,
)
from openpyxl.utils import get_column_letter

logger = logging.getLogger(__name__)

# ── Style Constants ──────────────────────────────────────────────────────
FONT_TITLE = Font(name="Calibri", size=18, bold=True, color="1A1A2E")
FONT_SUBTITLE = Font(name="Calibri", size=12, bold=False, color="4A4A5A")
FONT_HEADER = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
FONT_SUBHEADER = Font(name="Calibri", size=11, bold=True, color="1A1A2E")
FONT_BODY = Font(name="Calibri", size=10)
FONT_TOTAL = Font(name="Calibri", size=10, bold=True)
FONT_FOOTER = Font(name="Calibri", size=9, italic=True, color="888888")

FILL_HEADER = PatternFill("solid", fgColor="2D3748")
FILL_ALT_ROW = PatternFill("solid", fgColor="F7FAFC")
FILL_TOTAL = PatternFill("solid", fgColor="EBF4FF")
FILL_CRITICAL = PatternFill("solid", fgColor="FED7D7")
FILL_HIGH = PatternFill("solid", fgColor="FEEBC8")
FILL_MEDIUM = PatternFill("solid", fgColor="FEFCBF")
FILL_LOW = PatternFill("solid", fgColor="C6F6D5")
FILL_INFO = PatternFill("solid", fgColor="E9D8FD")

SEVERITY_FILLS = {
    "critical": FILL_CRITICAL,
    "high": FILL_HIGH,
    "medium": FILL_MEDIUM,
    "low": FILL_LOW,
    "info": FILL_INFO,
}

ALIGN_CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
ALIGN_LEFT = Alignment(horizontal="left", vertical="center", wrap_text=True)
ALIGN_RIGHT = Alignment(horizontal="right", vertical="center")

THIN_BORDER = Border(
    left=Side(style="thin", color="D2D6DC"),
    right=Side(style="thin", color="D2D6DC"),
    top=Side(style="thin", color="D2D6DC"),
    bottom=Side(style="thin", color="D2D6DC"),
)
BOTTOM_BORDER = Border(bottom=Side(style="medium", color="2D3748"))

# Indian number format
INR_FORMAT = '#,##0.00'


def _format_inr(amount: Decimal | float) -> str:
    """Format amount in Indian numbering system (lakhs/crores)."""
    val = float(amount)
    if abs(val) >= 1_00_00_000:
        return f"₹{val/1_00_00_000:,.2f} Cr"
    elif abs(val) >= 1_00_000:
        return f"₹{val/1_00_000:,.2f} L"
    else:
        return f"₹{val:,.2f}"


def _auto_width(ws, min_width: int = 10, max_width: int = 50) -> None:
    """Auto-adjust column widths based on content."""
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        adjusted = min(max(max_len + 2, min_width), max_width)
        ws.column_dimensions[col_letter].width = adjusted


class ExcelBuilder:
    """Builds professional audit/financial statement Excel workbooks."""

    def __init__(self):
        self.wb = Workbook()
        # Remove default sheet
        self.wb.remove(self.wb.active)

    def add_cover_page(
        self,
        company_name: str,
        financial_year: str,
        report_title: str = "Audit Report & Financial Statements",
        generated_by: str = "FinSight",
    ) -> None:
        """Add a professional cover page."""
        ws = self.wb.create_sheet("Cover")

        # Merge cells for title area
        ws.merge_cells("B3:F3")
        ws.merge_cells("B5:F5")
        ws.merge_cells("B7:F7")
        ws.merge_cells("B9:F9")
        ws.merge_cells("B11:F11")

        ws["B3"] = company_name
        ws["B3"].font = FONT_TITLE

        ws["B5"] = report_title
        ws["B5"].font = Font(name="Calibri", size=14, bold=True, color="4A4A5A")

        ws["B7"] = f"Financial Year: {financial_year}"
        ws["B7"].font = FONT_SUBTITLE

        from datetime import datetime
        ws["B9"] = f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}"
        ws["B9"].font = FONT_SUBTITLE

        ws["B11"] = f"Prepared by: {generated_by}"
        ws["B11"].font = FONT_SUBTITLE

        # Disclaimer
        ws.merge_cells("B14:F16")
        ws["B14"] = (
            "CONFIDENTIAL: This report has been generated by FinSight for "
            "internal audit and review purposes. The contents should be "
            "verified independently before reliance."
        )
        ws["B14"].font = FONT_FOOTER
        ws["B14"].alignment = Alignment(wrap_text=True)

        ws.column_dimensions["B"].width = 40

    def add_balance_sheet(self, bs_data: dict[str, Any]) -> None:
        """Add a Schedule III formatted Balance Sheet sheet."""
        ws = self.wb.create_sheet("Balance Sheet")
        row = 1

        # Title
        ws.merge_cells(f"A{row}:D{row}")
        ws[f"A{row}"] = "BALANCE SHEET"
        ws[f"A{row}"].font = FONT_TITLE
        row += 1

        ws.merge_cells(f"A{row}:D{row}")
        ws[f"A{row}"] = f"As at the end of Financial Year {bs_data.get('financial_year', '')}"
        ws[f"A{row}"].font = FONT_SUBTITLE
        row += 2

        # Headers
        headers = ["Particulars", "", "Note", "Amount (₹)"]
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=row, column=col_idx, value=header)
            cell.font = FONT_HEADER
            cell.fill = FILL_HEADER
            cell.alignment = ALIGN_CENTER
            cell.border = THIN_BORDER
        row += 1

        # ── I. EQUITY AND LIABILITIES ────────────────────────────────
        ws.cell(row=row, column=1, value="I. EQUITY AND LIABILITIES").font = FONT_SUBHEADER
        row += 1

        eq_liab = bs_data.get("equity_and_liabilities", {})
        for category, items in eq_liab.items():
            ws.cell(row=row, column=1, value=f"  {category}").font = FONT_SUBHEADER
            row += 1
            for line_item, amount in items.items():
                ws.cell(row=row, column=1, value=f"    {line_item}").font = FONT_BODY
                ws.cell(row=row, column=1).alignment = ALIGN_LEFT
                cell = ws.cell(row=row, column=4, value=float(amount))
                cell.font = FONT_BODY
                cell.number_format = INR_FORMAT
                cell.alignment = ALIGN_RIGHT
                cell.border = THIN_BORDER
                row += 1

        # Total Equity & Liabilities
        ws.cell(row=row, column=1, value="TOTAL EQUITY AND LIABILITIES").font = FONT_TOTAL
        total_el = float(bs_data.get("total_equity_liabilities", 0))
        cell = ws.cell(row=row, column=4, value=total_el)
        cell.font = FONT_TOTAL
        cell.number_format = INR_FORMAT
        cell.fill = FILL_TOTAL
        cell.border = BOTTOM_BORDER
        row += 2

        # ── II. ASSETS ───────────────────────────────────────────────
        ws.cell(row=row, column=1, value="II. ASSETS").font = FONT_SUBHEADER
        row += 1

        assets = bs_data.get("assets", {})
        for category, items in assets.items():
            ws.cell(row=row, column=1, value=f"  {category}").font = FONT_SUBHEADER
            row += 1
            for line_item, amount in items.items():
                ws.cell(row=row, column=1, value=f"    {line_item}").font = FONT_BODY
                cell = ws.cell(row=row, column=4, value=float(amount))
                cell.font = FONT_BODY
                cell.number_format = INR_FORMAT
                cell.alignment = ALIGN_RIGHT
                cell.border = THIN_BORDER
                row += 1

        # Total Assets
        ws.cell(row=row, column=1, value="TOTAL ASSETS").font = FONT_TOTAL
        total_a = float(bs_data.get("total_assets", 0))
        cell = ws.cell(row=row, column=4, value=total_a)
        cell.font = FONT_TOTAL
        cell.number_format = INR_FORMAT
        cell.fill = FILL_TOTAL
        cell.border = BOTTOM_BORDER
        row += 2

        # Balance check
        is_balanced = bs_data.get("is_balanced", False)
        ws.cell(
            row=row, column=1,
            value="✓ Assets = Equity + Liabilities" if is_balanced else "✗ BALANCE SHEET DOES NOT TALLY"
        ).font = Font(
            name="Calibri", size=10, bold=True,
            color="38A169" if is_balanced else "E53E3E"
        )

        # Column widths
        ws.column_dimensions["A"].width = 45
        ws.column_dimensions["B"].width = 5
        ws.column_dimensions["C"].width = 8
        ws.column_dimensions["D"].width = 20
        ws.freeze_panes = "A5"

    def add_profit_and_loss(self, pl_data: dict[str, Any]) -> None:
        """Add a Schedule III formatted P&L Statement sheet."""
        ws = self.wb.create_sheet("Profit & Loss")
        row = 1

        ws.merge_cells(f"A{row}:D{row}")
        ws[f"A{row}"] = "STATEMENT OF PROFIT AND LOSS"
        ws[f"A{row}"].font = FONT_TITLE
        row += 1

        ws.merge_cells(f"A{row}:D{row}")
        ws[f"A{row}"] = f"For the Financial Year {pl_data.get('financial_year', '')}"
        ws[f"A{row}"].font = FONT_SUBTITLE
        row += 2

        # Headers
        for col_idx, header in enumerate(["Particulars", "", "Note", "Amount (₹)"], 1):
            cell = ws.cell(row=row, column=col_idx, value=header)
            cell.font = FONT_HEADER
            cell.fill = FILL_HEADER
            cell.alignment = ALIGN_CENTER
            cell.border = THIN_BORDER
        row += 1

        # Revenue
        ws.cell(row=row, column=1, value="INCOME").font = FONT_SUBHEADER
        row += 1
        revenue = pl_data.get("revenue", {})
        for item, amount in revenue.items():
            ws.cell(row=row, column=1, value=f"  {item}").font = FONT_BODY
            cell = ws.cell(row=row, column=4, value=float(amount))
            cell.font = FONT_BODY
            cell.number_format = INR_FORMAT
            cell.alignment = ALIGN_RIGHT
            cell.border = THIN_BORDER
            row += 1

        ws.cell(row=row, column=1, value="Total Income").font = FONT_TOTAL
        cell = ws.cell(row=row, column=4, value=float(pl_data.get("total_revenue", 0)))
        cell.font = FONT_TOTAL
        cell.number_format = INR_FORMAT
        cell.fill = FILL_TOTAL
        cell.border = BOTTOM_BORDER
        row += 2

        # Expenses
        ws.cell(row=row, column=1, value="EXPENSES").font = FONT_SUBHEADER
        row += 1
        expenses = pl_data.get("expenses", {})
        for item, amount in expenses.items():
            ws.cell(row=row, column=1, value=f"  {item}").font = FONT_BODY
            cell = ws.cell(row=row, column=4, value=float(amount))
            cell.font = FONT_BODY
            cell.number_format = INR_FORMAT
            cell.alignment = ALIGN_RIGHT
            cell.border = THIN_BORDER
            row += 1

        ws.cell(row=row, column=1, value="Total Expenses").font = FONT_TOTAL
        cell = ws.cell(row=row, column=4, value=float(pl_data.get("total_expenses", 0)))
        cell.font = FONT_TOTAL
        cell.number_format = INR_FORMAT
        cell.fill = FILL_TOTAL
        cell.border = BOTTOM_BORDER
        row += 2

        # Profit figures
        for label, key in [
            ("Profit Before Tax", "profit_before_tax"),
            ("Tax Expense", "tax_expense"),
            ("Net Profit / (Loss)", "net_profit"),
        ]:
            ws.cell(row=row, column=1, value=label).font = FONT_TOTAL
            val = float(pl_data.get(key, 0))
            cell = ws.cell(row=row, column=4, value=val)
            cell.font = FONT_TOTAL
            cell.number_format = INR_FORMAT
            if key == "net_profit":
                cell.fill = FILL_TOTAL
                cell.border = BOTTOM_BORDER
            row += 1

        ws.column_dimensions["A"].width = 45
        ws.column_dimensions["D"].width = 20
        ws.freeze_panes = "A5"

    def add_trial_balance(self, ledgers: list[dict]) -> None:
        """Add a trial balance sheet with all ledger details."""
        ws = self.wb.create_sheet("Trial Balance")
        row = 1

        ws.merge_cells(f"A{row}:F{row}")
        ws[f"A{row}"] = "TRIAL BALANCE"
        ws[f"A{row}"].font = FONT_TITLE
        row += 2

        # Headers
        headers = ["Ledger Name", "Group", "Opening Balance", "Debit", "Credit", "Closing Balance"]
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=row, column=col_idx, value=header)
            cell.font = FONT_HEADER
            cell.fill = FILL_HEADER
            cell.alignment = ALIGN_CENTER
            cell.border = THIN_BORDER
        row += 1

        totals = {"opening": Decimal("0"), "debit": Decimal("0"),
                  "credit": Decimal("0"), "closing": Decimal("0")}

        for i, ledger in enumerate(ledgers):
            fill = FILL_ALT_ROW if i % 2 else None
            ws.cell(row=row, column=1, value=ledger["name"]).font = FONT_BODY
            ws.cell(row=row, column=2, value=ledger["group"]).font = FONT_BODY

            for col_idx, key in [(3, "opening_balance"), (4, "debit_total"),
                                  (5, "credit_total"), (6, "closing_balance")]:
                val = float(ledger.get(key, 0))
                cell = ws.cell(row=row, column=col_idx, value=val)
                cell.font = FONT_BODY
                cell.number_format = INR_FORMAT
                cell.alignment = ALIGN_RIGHT

            if fill:
                for col_idx in range(1, 7):
                    ws.cell(row=row, column=col_idx).fill = fill

            for col_idx in range(1, 7):
                ws.cell(row=row, column=col_idx).border = THIN_BORDER

            totals["opening"] += Decimal(str(ledger.get("opening_balance", 0)))
            totals["debit"] += Decimal(str(ledger.get("debit_total", 0)))
            totals["credit"] += Decimal(str(ledger.get("credit_total", 0)))
            totals["closing"] += Decimal(str(ledger.get("closing_balance", 0)))
            row += 1

        # Totals row
        ws.cell(row=row, column=1, value="TOTAL").font = FONT_TOTAL
        for col_idx, key in [(3, "opening"), (4, "debit"), (5, "credit"), (6, "closing")]:
            cell = ws.cell(row=row, column=col_idx, value=float(totals[key]))
            cell.font = FONT_TOTAL
            cell.number_format = INR_FORMAT
            cell.fill = FILL_TOTAL
            cell.border = BOTTOM_BORDER

        _auto_width(ws)
        ws.freeze_panes = "A4"

    def add_audit_findings(self, findings: list[dict], risk_score: float = 0) -> None:
        """Add audit findings sheets (summary + detail)."""
        # ── Summary Sheet ────────────────────────────────────────────
        ws = self.wb.create_sheet("Audit Summary")
        row = 1

        ws.merge_cells(f"A{row}:D{row}")
        ws[f"A{row}"] = "AUDIT FINDINGS SUMMARY"
        ws[f"A{row}"].font = FONT_TITLE
        row += 2

        # Risk Score
        ws.cell(row=row, column=1, value="Overall Risk Score:").font = FONT_SUBHEADER
        score_cell = ws.cell(row=row, column=2, value=f"{risk_score:.1f} / 100")
        score_cell.font = Font(
            name="Calibri", size=14, bold=True,
            color="E53E3E" if risk_score > 60 else ("ED8936" if risk_score > 30 else "38A169")
        )
        row += 2

        # Severity summary
        severity_counts = {}
        for f in findings:
            sev = f.get("severity", "info")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        ws.cell(row=row, column=1, value="Severity").font = FONT_HEADER
        ws.cell(row=row, column=1).fill = FILL_HEADER
        ws.cell(row=row, column=2, value="Count").font = FONT_HEADER
        ws.cell(row=row, column=2).fill = FILL_HEADER
        row += 1

        for sev in ["critical", "high", "medium", "low", "info"]:
            count = severity_counts.get(sev, 0)
            ws.cell(row=row, column=1, value=sev.upper()).font = FONT_BODY
            ws.cell(row=row, column=1).fill = SEVERITY_FILLS.get(sev, FILL_INFO)
            ws.cell(row=row, column=2, value=count).font = FONT_BODY
            ws.cell(row=row, column=2).alignment = ALIGN_CENTER
            row += 1

        ws.cell(row=row, column=1, value="TOTAL").font = FONT_TOTAL
        ws.cell(row=row, column=2, value=len(findings)).font = FONT_TOTAL
        ws.cell(row=row, column=2).fill = FILL_TOTAL
        row += 2

        # Category summary
        category_counts = {}
        for f in findings:
            cat = f.get("category", "Other")
            category_counts[cat] = category_counts.get(cat, 0) + 1

        ws.cell(row=row, column=1, value="Category").font = FONT_HEADER
        ws.cell(row=row, column=1).fill = FILL_HEADER
        ws.cell(row=row, column=2, value="Findings").font = FONT_HEADER
        ws.cell(row=row, column=2).fill = FILL_HEADER
        row += 1

        for cat, count in sorted(category_counts.items()):
            ws.cell(row=row, column=1, value=cat).font = FONT_BODY
            ws.cell(row=row, column=2, value=count).font = FONT_BODY
            row += 1

        ws.column_dimensions["A"].width = 30
        ws.column_dimensions["B"].width = 15

        # ── Detail Sheet ─────────────────────────────────────────────
        ws2 = self.wb.create_sheet("Audit Findings Detail")
        row = 1

        ws2.merge_cells(f"A{row}:G{row}")
        ws2[f"A{row}"] = "DETAILED AUDIT FINDINGS"
        ws2[f"A{row}"].font = FONT_TITLE
        row += 2

        detail_headers = [
            "Rule ID", "Severity", "Category", "Title",
            "Ledger", "Amount (₹)", "Recommendation"
        ]
        for col_idx, header in enumerate(detail_headers, 1):
            cell = ws2.cell(row=row, column=col_idx, value=header)
            cell.font = FONT_HEADER
            cell.fill = FILL_HEADER
            cell.alignment = ALIGN_CENTER
            cell.border = THIN_BORDER
        row += 1

        for finding in findings:
            sev = finding.get("severity", "info")
            fill = SEVERITY_FILLS.get(sev)

            ws2.cell(row=row, column=1, value=finding.get("rule_id", "")).font = FONT_BODY
            sev_cell = ws2.cell(row=row, column=2, value=sev.upper())
            sev_cell.font = FONT_BODY
            if fill:
                sev_cell.fill = fill
            ws2.cell(row=row, column=3, value=finding.get("category", "")).font = FONT_BODY
            ws2.cell(row=row, column=4, value=finding.get("title", "")).font = FONT_BODY
            ws2.cell(row=row, column=4).alignment = ALIGN_LEFT
            ws2.cell(row=row, column=5, value=finding.get("ledger_name", "")).font = FONT_BODY

            amt = finding.get("amount")
            if amt is not None:
                cell = ws2.cell(row=row, column=6, value=float(amt))
                cell.number_format = INR_FORMAT
            cell_rec = ws2.cell(row=row, column=7, value=finding.get("recommendation", ""))
            cell_rec.font = FONT_BODY
            cell_rec.alignment = ALIGN_LEFT

            for col_idx in range(1, 8):
                ws2.cell(row=row, column=col_idx).border = THIN_BORDER
            row += 1

        _auto_width(ws2)
        ws2.freeze_panes = "A4"

    def save(self) -> bytes:
        """Save the workbook to a bytes buffer and return it."""
        buffer = BytesIO()
        self.wb.save(buffer)
        buffer.seek(0)
        return buffer.read()
