"""Initial migration

Revision ID: c0fcbee365c5
Revises: 
Create Date: 2026-06-08 11:51:37.582103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fcbee365c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tally_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('tally_host', sa.String(length=255), nullable=False),
    sa.Column('tally_port', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('company_number', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'AUDITOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rules_executed', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.Enum('AUDIT_REPORT', 'FINANCIAL_STATEMENTS', 'COMBINED', name='reporttype'), nullable=False),
    sa.Column('report_format', sa.Enum('XLSX', 'PDF', name='reportformat'), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_iii_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('tally_group', sa.String(length=255), nullable=False),
    sa.Column('section', sa.Enum('BALANCE_SHEET', 'PROFIT_AND_LOSS', name='schedulesection'), nullable=False),
    sa.Column('schedule_iii_line', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_auto_mapped', sa.Boolean(), nullable=False),
    sa.Column('mapping_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('groups_synced', sa.Integer(), nullable=False),
    sa.Column('ledgers_synced', sa.Integer(), nullable=False),
    sa.Column('vouchers_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tally_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('tally_guid', sa.String(length=255), nullable=True),
    sa.Column('alter_id', sa.Integer(), nullable=True),
    sa.Column('is_revenue', sa.Boolean(), nullable=False),
    sa.Column('is_deemedpositive', sa.Boolean(), nullable=False),
    sa.Column('affects_gross_profit', sa.Boolean(), nullable=False),
    sa.Column('sort_position', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tally_ledgers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=False),
    sa.Column('tally_guid', sa.String(length=255), nullable=True),
    sa.Column('alter_id', sa.Integer(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('debit_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('is_bill_wise', sa.Boolean(), nullable=False),
    sa.Column('is_cost_centres_on', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tally_ledgers_name'), 'tally_ledgers', ['name'], unique=False)
    op.create_table('tally_vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tally_guid', sa.String(length=255), nullable=True),
    sa.Column('alter_id', sa.Integer(), nullable=True),
    sa.Column('voucher_type', sa.String(length=100), nullable=False),
    sa.Column('voucher_number', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('party_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tally_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tally_vouchers_date'), 'tally_vouchers', ['date'], unique=False)
    op.create_table('audit_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('audit_run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_rule_id'), 'audit_findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_severity'), 'audit_findings', ['severity'], unique=False)
    op.create_table('tally_voucher_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_debit', sa.Boolean(), nullable=False),
    sa.Column('voucher_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['tally_ledgers.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['tally_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tally_voucher_entries')
    op.drop_index(op.f('ix_audit_findings_severity'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_rule_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_tally_vouchers_date'), table_name='tally_vouchers')
    op.drop_table('tally_vouchers')
    op.drop_index(op.f('ix_tally_ledgers_name'), table_name='tally_ledgers')
    op.drop_table('tally_ledgers')
    op.drop_table('tally_groups')
    op.drop_table('sync_jobs')
    op.drop_table('schedule_iii_mappings')
    op.drop_table('generated_reports')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tally_clients')
    op.drop_table('organizations')
    # ### end Alembic commands ###
